### ISSUE TITLE
antd修改默认样式的方法

### ISSUE THREAD

**Issue by xinglee23** [xinglee23/myBlog#4]
# antd修改默认样式的方法
1、直接style覆盖,eg:
```js
<Button style={
  width: '130px',
  height: '40px',
  marginTop: '16px',
  marginRight: '-86px',
  fontSize: '14px'
} />
```
2、golbal全部样式覆盖
找到样式在antd中的className并将其覆盖
```css
:global {
  .ant-table-thead > tr > th {
    /* 具体的样式 */
    border-bottom: 1px solid #e9e9e9;
  }
}
```
3、[官网介绍的一些方法](https://pro.ant.design/docs/style-cn#%E8%A6%86%E7%9B%96%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F)
        
4、如果有类似原生主题不符合开发的可以自已定制主题，官网也提供了相关的方法<br/>
&emsp;&emsp;[主题定制](https://ant.design/docs/react/customize-theme-cn)
